### ISSUE TITLE
Wrong docker-compose command in README.md documentation

### ISSUE THREAD

**Issue by migthymax** [walkero-gr/odysseyOnDocker#7]
Hi,

just a minor correction hint, which took me some minutes to figure out, because i haven't much experience with docker.
In the README.md documentation is a typo in the order of the arguments. Currently written is:

` docker-compose odysseyondocker exec bash`

Bit the first and second argument muts be changed, so that it looks like:

`docker-compose exec odysseyondocker bash`

best regards

**Comment by walkero-gr** [comment]
Thank you so much for this comment. Will fix it asap.
