### ISSUE TITLE
Missing header uchar.h

### ISSUE THREAD

**Issue by timocock** [walkero-gr/odysseyOnDocker#8]
Getting error after fresh install and following instructions exactly:

                 from /opt/code/Odyssey/odyssey-r155188-1.23/Source/JavaScriptCore/runtime/WriteBarrier.h:31,
                 from /opt/code/Odyssey/odyssey-r155188-1.23/Source/JavaScriptCore/runtime/PropertyStorage.h:29,
                 from /opt/code/Odyssey/odyssey-r155188-1.23/Source/JavaScriptCore/runtime/IndexingHeader.h:29,
                 from /opt/code/Odyssey/odyssey-r155188-1.23/Source/JavaScriptCore/runtime/ArrayConventions.h:24,
                 from /opt/code/Odyssey/odyssey-r155188-1.23/Source/JavaScriptCore/runtime/JSArray.h:24,
                 from /opt/code/Odyssey/odyssey-r155188-1.23/Source/JavaScriptCore/bytecode/ArrayProfile.h:30,
                 from /opt/code/Odyssey/odyssey-r155188-1.23/Source/JavaScriptCore/llint/LLIntOffsetsExtractor.cpp:28:
/opt/code/Odyssey/odyssey-r155188-1.23/build/generated_link/BAL/wtf/unicode/Unicode.h:29:10: fatal error: unicode/uchar.h: No such file or directory
 #include <unicode/uchar.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by walkero-gr** [comment]
@timocock Weird. I checked my local dev and that file doesn't have this include. I will make a new installation and try that again. Will be back with news.

**Comment by timocock** [comment]
Yeah folder seems not to contain that one
root@bec375e15417:/opt/code/Odyssey/odyssey-r155188-1.23/build/generated_link/BAL/wtf/unicode# ls
CharacterNames.h  Collator.h  Encoding.h  ScriptCodesFrom.h  Unicode.h  UTF8.h

**Comment by timocock** [comment]
> @timocock Weird. I checked my local dev and that file doesn't have this include. I will make a new installation and try that again. Will be back with news.

Hi wondered if you had looked into this yet. Also, where is best place to reach whole Odyssey for OS4 team?

**Comment by walkero-gr** [comment]
Hello @timocock . Can you please tell me which repo did you use to clone Odyssey code? If you used the https://github.com/kas1e/Odyssey I would like to inform you that you will not be able to compile Odyssey with this docker images, because it lacks the code of the PR https://github.com/kas1e/Odyssey/pull/22.

I have those changes on my fork at https://github.com/walkero-gr/Odyssey/tree/Build-on-docker

**Comment by timocock** [comment]
I followed the instructions in the readme to the letter, so if the readme is out of date please update it. If it is not out of date, then no, it isn't working from a clean install for the reasons I set out above.

**Comment by walkero-gr** [comment]
@timocock 
You were right. There was an missing part on the guide, which I updated. When you clone the project you need to switch to Build-on-docker branch. This way it builds just fine, which I just did from scratch.
Thank you for your recommendation.

**Comment by timocock** [comment]
Thanks, will try again shortly. Would love to discuss with you and other Odyssey team members how I can contribute.

**Comment by walkero-gr** [comment]
@timocock 
I would propose you to visit amigans.net and open discussion there, where the main developers are and they can guide you more. From my side I didn't contribute much so far. Just created this environment for anyone who wants to setup a dev environment fast enough

**Comment by timocock** [comment]
> @timocock
> I would propose you to visit amigans.net and open discussion there, where the main developers are and they can guide you more. From my side I didn't contribute much so far. Just created this environment for anyone who wants to setup a dev environment fast enough

Hi Walkero did you see Jacek has made his webkit port repository open and available under BSD license now?

**Comment by walkero-gr** [comment]
@timocock Really? That's awesome news. I haven't seen that. Can you please share the link?

**Comment by timocock** [comment]
https://github.com/jacadcaps/webkitty
